spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/supportdb
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: pN2qS7vm98Bq0W7Vm2P0vH8m7dPQsB9Z+oP7FqLzXKo=
  expiration: 3600000
